# Generated by Django 4.1.5 on 2023-03-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_loyaltypoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='LoyaltyPoints',
        ),
    ]
